//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDesarrollo1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_desarrollofinalEntities : DbContext
    {
        public db_desarrollofinalEntities()
            : base("name=db_desarrollofinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tb_Artistas> Tb_Artistas { get; set; }
        public virtual DbSet<Tb_CompTelefono> Tb_CompTelefono { get; set; }
        public virtual DbSet<Tb_EmpTarjeta> Tb_EmpTarjeta { get; set; }
        public virtual DbSet<Tb_Eventos> Tb_Eventos { get; set; }
        public virtual DbSet<Tb_Persona> Tb_Persona { get; set; }
        public virtual DbSet<Tb_Publicacion> Tb_Publicacion { get; set; }
        public virtual DbSet<Tb_RolUsuario> Tb_RolUsuario { get; set; }
        public virtual DbSet<Tb_Ticket> Tb_Ticket { get; set; }
        public virtual DbSet<Tb_TipoEvento> Tb_TipoEvento { get; set; }
    }
}
