//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDesarrollo1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Artistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Artistas()
        {
            this.Tb_Eventos = new HashSet<Tb_Eventos>();
        }
    
        public int Artista_id { get; set; }
        public string Artista_nombre { get; set; }
        public string Artista_apellido { get; set; }
        public Nullable<int> CompTelefono_id_FK { get; set; }
        public string Artista_Telefono { get; set; }
    
        public virtual Tb_CompTelefono Tb_CompTelefono { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Eventos> Tb_Eventos { get; set; }
    }
}
