//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDesarrollo1._0
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_Publicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Publicacion()
        {
            this.Tb_Ticket = new HashSet<Tb_Ticket>();
        }
    
        public int Publicacion_id { get; set; }
        [Required(ErrorMessage = "Formato de fecha 09/11/2019")]
        public System.DateTime Publicacion_dia { get; set; }
        [Required(ErrorMessage = "Formato de hora 13:35")]
        public System.TimeSpan Publicacion_hora { get; set; }
        [Required(ErrorMessage = "Indique el precio al publico")]
        public decimal Publicacion_precio { get; set; }
        public int Evento_id { get; set; }
    
        public virtual Tb_Eventos Tb_Eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Ticket> Tb_Ticket { get; set; }
    }
}
