//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDesarrollo1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Ticket
    {
        public int Ticket_id { get; set; }
        public int Persona_id { get; set; }
        public string ticket_fila { get; set; }
        public Nullable<int> ticket_columna { get; set; }
        public Nullable<int> Publicacion_id_fk { get; set; }
    
        public virtual Tb_Persona Tb_Persona { get; set; }
        public virtual Tb_Publicacion Tb_Publicacion { get; set; }
    }
}
